<?php

/**
 * Implements hook_permission().
 *
 * @return Assoc
 *   permission items.
 */
function utsav_booking_permission() {
  return array(
    'administer utsav_booking' => array(
      'title' => t("Administer utsav booking"),
      'description' => t('Perform administration tasks for the module utsav booking.'),
    ),
  );
}

/**
 * Implements hook_menu().
 *
 * @return Assoc
 *   menu items.
 */
function utsav_booking_menu() {
  $items = array();
  $items['admin/config/user-interface/utsav_booking'] = array(
    'title' => 'Utsav Booking',
    'description' => "Controls settings for the module utsav booking",
    'file' => 'includes/utsav_booking.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('utsav_booking_admin_configure'),
    'access arguments' => array('administer utsav_booking'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 *
 * @return Assoc
 *   the blocks' info.
 */
function utsav_booking_block_info() {
  $block = array();
  $block['utsav_booking'] = array(
    'info' => t('Utsav Booking'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $block;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 *   the identifier of the requested block.
 *
 * @return Assoc
 *   the requested block's view.
 */
function utsav_booking_block_view($delta = NULL) {
  $block = array();
  switch ($delta) {
    case 'utsav_booking':
      require_once 'includes/utsav_booking.blocks.inc';
      $block['subject'] = NULL;
      $block['content'] = _utsav_booking_block();
      break;
  }
  return $block;
}



